Repository fga-eps-mds/2022-1-PokeRanking, pull requests merged in 2022-08, with the labels that each got.

#59 :memo: atualização do documento de visão
  docs/Documentação/documento-de-visao.md
Labels: documentation

#69 :sparkles: US02, US03 e US04 no Backend
  pokeranking/server/Controller/home_controller.js
  pokeranking/server/routes/criaturaRoutes.js
Labels: enhancement, BackEnd

#74 :sparkles: Busca e exibição de Pokémon por nome ou código
  pokeranking/server/Controller/home_controller.js
  pokeranking/server/index.js
  pokeranking/server/routes/criaturaRoutes.js
Labels: enhancement, BackEnd

#75 ✨🎨 Landing Page e estrutura de pastas do Front
  pokeranking/package-lock.json
  pokeranking/package.json
  pokeranking/src/App.jsx
  pokeranking/src/Assets/Logo_Principal.png
  pokeranking/src/Assets/logo-branco.png
  pokeranking/src/Assets/logo-principal.png
  pokeranking/src/Assets/reset.css
  pokeranking/src/Assets/shape.png
  pokeranking/src/Components/FiltroDisplay/index.jsx
  pokeranking/src/Components/FiltroDisplay/style.css
  pokeranking/src/Components/Footer/index.jsx
  pokeranking/src/Components/Footer/style.css
  pokeranking/src/Components/Header/index.jsx
  pokeranking/src/Components/Header/style.css
  pokeranking/src/Components/LogoDisplay/index.jsx
  pokeranking/src/Components/LogoDisplay/style.css
  pokeranking/src/Components/PokemonDisplay/index.jsx
  pokeranking/src/Components/PokemonDisplay/style.css
  pokeranking/src/Pages/Home/index.jsx
  pokeranking/src/Pages/Home/style.css
  pokeranking/src/Pages/Ranking/index.jsx
  pokeranking/src/Pages/Ranking/style.css
  pokeranking/src/app.css
  pokeranking/src/index.css
  pokeranking/src/index.js
  pokeranking/src/pages/Home/Index.js
  pokeranking/src/pages/Home/style.css
Labels: enhancement, FrontEnd

#84 Feat 78 sidebar menu
  pokeranking/src/Assets/close.png
  pokeranking/src/Assets/como-usar.png
  pokeranking/src/Assets/comparacao.png
  pokeranking/src/Assets/equipe.png
  pokeranking/src/Assets/home.png
  pokeranking/src/Assets/menu.png
  pokeranking/src/Assets/ranking.png
  pokeranking/src/Assets/sidebar-logo.png
  pokeranking/src/Components/Footer/style.css
  pokeranking/src/Components/Header/SidebarData.js
  pokeranking/src/Components/Header/index.jsx
  pokeranking/src/Components/Header/style.css
Labels: enhancement, FrontEnd

#87 :bug: Correção de bug na busca de criaturas por ranking e tipo
  pokeranking/server/Controller/home_controller.js
  pokeranking/server/Controller/services/Ordenacao_de_pokemon_por_status.js
  pokeranking/server/package.json
  pokeranking/server/tests/integracao.spec.js
  pokeranking/server/tests/mocks/pokemon_type_ranking.js
  pokeranking/server/tests/unitarios.spec.js
Labels: bug

#88 Feat 76 filtro interativo
  pokeranking/package-lock.json
  pokeranking/package.json
  pokeranking/src/Assets/Pokeball-Icon.png
  pokeranking/src/Assets/PokemonTypeIcons/TypeBug.png
  pokeranking/src/Assets/PokemonTypeIcons/TypeDark.png
  pokeranking/src/Assets/PokemonTypeIcons/TypeDragon.png
  pokeranking/src/Assets/PokemonTypeIcons/TypeElectric.png
  pokeranking/src/Assets/PokemonTypeIcons/TypeFairy.png
  pokeranking/src/Assets/PokemonTypeIcons/TypeFighting.png
  pokeranking/src/Assets/PokemonTypeIcons/TypeFire.png
  pokeranking/src/Assets/PokemonTypeIcons/TypeFlying.png
  pokeranking/src/Assets/PokemonTypeIcons/TypeGhost.png
  pokeranking/src/Assets/PokemonTypeIcons/TypeGrass.png
  pokeranking/src/Assets/PokemonTypeIcons/TypeGround.png
  pokeranking/src/Assets/PokemonTypeIcons/TypeIce.png
  pokeranking/src/Assets/PokemonTypeIcons/TypeNormal.png
  pokeranking/src/Assets/PokemonTypeIcons/TypePoison.png
  pokeranking/src/Assets/PokemonTypeIcons/TypePsychic.png
  pokeranking/src/Assets/PokemonTypeIcons/TypeRock.png
  pokeranking/src/Assets/PokemonTypeIcons/TypeSteel.png
  pokeranking/src/Assets/PokemonTypeIcons/TypeWater.png
  pokeranking/src/Components/FiltroDetalheRegiao/index.jsx
  pokeranking/src/Components/FiltroDetalheRegiao/style.css
  pokeranking/src/Components/FiltroDetalheStatus/FiltroStatusData.js
  pokeranking/src/Components/FiltroDetalheStatus/index.jsx
  pokeranking/src/Components/FiltroDetalheStatus/style.css
  pokeranking/src/Components/FiltroDetalheTipo/FiltroTipoData.js
  pokeranking/src/Components/FiltroDetalheTipo/index.jsx
  pokeranking/src/Components/FiltroDetalheTipo/style.css
  pokeranking/src/Components/FiltroDisplay/index.jsx
  pokeranking/src/Components/FiltroDisplay/style.css
  pokeranking/src/Components/RankingDisplay/index.jsx
  pokeranking/src/Components/RankingDisplay/style.css
  pokeranking/src/Pages/Ranking/index.jsx
Labels: enhancement, FrontEnd

#92 Feat 91 filtro funcional
  pokeranking/src/App.jsx
  pokeranking/src/Components/FiltroDetalheStatus/FiltroStatusData.js
  pokeranking/src/Components/FiltroDetalheStatus/index.jsx
  pokeranking/src/Components/FiltroDetalheTipo/FiltroTipoData.js
  pokeranking/src/Components/FiltroDetalheTipo/index.jsx
  pokeranking/src/Components/FiltroDisplay/index.jsx
  pokeranking/src/Components/RankingDisplay/index.jsx
  pokeranking/src/Pages/Home/index.jsx
  pokeranking/src/Pages/Ranking/index.jsx
Labels: enhancement, FrontEnd
